USE [master]
GO
/****** Object:  Database [DemoDatabase]    Script Date: 1/24/2023 7:54:33 PM ******/
CREATE DATABASE [DemoDatabase]
 
EXEC [DemoDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DemoDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DemoDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DemoDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DemoDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DemoDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [DemoDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DemoDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DemoDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DemoDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DemoDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DemoDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DemoDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DemoDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DemoDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DemoDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DemoDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DemoDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DemoDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DemoDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DemoDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DemoDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DemoDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DemoDatabase] SET RECOVERY FULL 
GO
ALTER DATABASE [DemoDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [DemoDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DemoDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DemoDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DemoDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DemoDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DemoDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DemoDatabase', N'ON'
GO
ALTER DATABASE [DemoDatabase] SET QUERY_STORE = OFF
GO
USE [DemoDatabase]
GO
/****** Object:  Table [dbo].[country]    Script Date: 1/24/2023 7:54:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[country](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[state]    Script Date: 1/24/2023 7:54:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[state](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StateName] [varchar](50) NOT NULL,
	[CountryId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[state]  WITH CHECK ADD FOREIGN KEY([CountryId])
REFERENCES [dbo].[country] ([Id])
GO
USE [master]
GO
ALTER DATABASE [DemoDatabase] SET  READ_WRITE 
GO
